# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bme31/Desktop/shudianshiyan4/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/bme31/Desktop/shudianshiyan4/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/bme31/Desktop/digital 4/lab41.v}}
read_xdc {{C:/Users/bme31/Desktop/digital 4/DSDB (1).xdc}}
set_property used_in_implementation false [get_files {{C:/Users/bme31/Desktop/digital 4/DSDB (1).xdc}}]

catch { write_hwdef -file seg7ment_top.hwdef }
synth_design -top seg7ment_top -part xc7z020clg484-1
write_checkpoint -noxdef seg7ment_top.dcp
catch { report_utilization -file seg7ment_top_utilization_synth.rpt -pb seg7ment_top_utilization_synth.pb }
