# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/BME/Desktop/lcd/lcd.cache/wt [current_project]
set_property parent.project_path C:/Users/BME/Desktop/lcd/lcd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/BME/Desktop/lcd/lcd.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/BME/Desktop/lcd/lcd.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/BME/Desktop/模电2/tft_disp.v
  C:/Users/BME/Desktop/模电2/tft_ctrl.v
  C:/Users/BME/Desktop/模电2/tft_char.v
}
read_xdc C:/Users/BME/Desktop/模电2/DSDB.xdc
set_property used_in_implementation false [get_files C:/Users/BME/Desktop/模电2/DSDB.xdc]

catch { write_hwdef -file tft_char.hwdef }
synth_design -top tft_char -part xc7z020clg484-1
write_checkpoint -noxdef tft_char.dcp
catch { report_utilization -file tft_char_utilization_synth.rpt -pb tft_char_utilization_synth.pb }
