# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bme31/Desktop/shudianshiyan4/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/bme31/Desktop/shudianshiyan4/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/bme31/Desktop/shudianshiyan4/project_3/project_3.srcs/sources_1/imports/digital 4/lab43.v}}
read_xdc C:/Users/bme31/Desktop/shudianshiyan4/project_3/project_3.srcs/constrs_1/new/exp3.xdc
set_property used_in_implementation false [get_files C:/Users/bme31/Desktop/shudianshiyan4/project_3/project_3.srcs/constrs_1/new/exp3.xdc]

catch { write_hwdef -file clk_7segff_top.hwdef }
synth_design -top clk_7segff_top -part xc7z020clg484-1
write_checkpoint -noxdef clk_7segff_top.dcp
catch { report_utilization -file clk_7segff_top_utilization_synth.rpt -pb clk_7segff_top_utilization_synth.pb }
