# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bme317/Desktop/major_assignment/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/bme317/Desktop/major_assignment/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/bme317/Desktop/major_assignment/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/bme317/Desktop/major_assignment/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/bme317/Desktop/major_assignment/project_1/project_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/bme317/Desktop/major_assignment/project_1/project_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/i2c_controller.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/sine_wave.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/audio_effects.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/freq_div.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/i2c_config.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/audio_codec.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/import/uart_tx.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/import/uart_rx.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/debounce.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/i2c_top.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/edge_detect.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/freq_meter/count.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/import/UART_crl.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/111/Debounce.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/audio_recorder/recorder.v
  C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/sources_1/imports/freq_meter/top.v
}
read_xdc C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/constrs_1/imports/freq_meter/DSDB.xdc
set_property used_in_implementation false [get_files C:/Users/bme317/Desktop/major_assignment/project_1/project_1.srcs/constrs_1/imports/freq_meter/DSDB.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7z020clg484-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
